# dust.toml: This file contains options pertaining to fitting the 
# MIR continuum model of spectra, including stellar & dust components.

# Each value has a "val" key which specifies the starting value,
# "plim" specifies the lower and upper limits on the parameter, and
# "locked" specifies whether the parameter should be fixed or allowed
# to vary during the fit.

# stellar_continuum_temp: the blackbody temperature of the stellar
# continuum component of the model. Default: 5000 K.
[stellar_continuum_temp]
val = 5000.0
plim = [4999.9, 5000.1]
locked = true

# dust_continuum_temps: the blackbody temperatures of the dust
# continuum components of the model. 
# [[dust_continuum_temps]]
# val = 400.0
# plim = [35.0, 1500.0]
# locked = false
[[dust_continuum_temps]]
val = 200.0
plim = [35.0, 300.0]
locked = false
[[dust_continuum_temps]]
val = 100.0
plim = [35.0, 300.0]
locked = false

# PAHFIT Model: A series of profiles at fixed temperatures b/w 35-500 K
# [[dust_continuum_temps]]
# val = 500.0
# plim = [499.9, 500.1]
# locked = false
# [[dust_continuum_temps]]
# val = 300.0
# plim = [299.9, 300.1]
# locked = false
# [[dust_continuum_temps]]
# val = 200.0
# plim = [199.9, 200.1]
# locked = false
# [[dust_continuum_temps]]
# val = 135.0
# plim = [134.9, 135.1]
# locked = false
# [[dust_continuum_temps]]
# val = 90.0
# plim = [89.9, 90.1]
# locked = false
# [[dust_continuum_temps]]
# val = 65.0
# plim = [64.9, 65.1]
# locked = false
# [[dust_continuum_temps]]
# val = 50.0
# plim = [49.9, 50.1]
# locked = false
# [[dust_continuum_temps]]
# val = 40.0
# plim = [39.9, 40.1]
# locked = false
# [[dust_continuum_temps]]
# val = 35.0
# plim = [34.9, 35.1]
# locked = false

# power laws: should not be used in conjunction with blackbodies 
# (should be one or the other) since they are degenerate.
# [[power_law_indices]]
# val = 1.65
# plim = [-3.0, 3.0]
# locked = true

# template_amps: amplitude parameters for each template in the fit
# do NOT repeat entries here for different subchannel amplitudes -- those are handled internally
# and the initial value/limits/locked are assumed to be the same for each subchannel amplitude for a given
# template
[[template_amps]]
val = 1.0
plim = [0.5, 2.0]
locked = false

# dust_features: each of these specifies a Polycyclic Aromatic 
# Hydrocarbon (PAH) profile to include in the model. Each of these
# profiles has an associated "wave", or central wavelength in microns,
# and "fwhm", or full-width at half-maximum, also in microns. They
# are modeled using Drude profiles.  The names should follow the
# general format of "PAH_X.XX", filling in X with the central wavelength
# up to 2 decimal places (or more if necessary).

[dust_features."PAH_3.29".wave]
val = 3.29
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_3.29".fwhm]
val = 0.050
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_5.25".wave]
val = 5.253
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.25".fwhm]
val = 0.032
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_5.27".wave]
val = 5.266
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.27".fwhm]
val = 0.138
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_5.70".wave]
val = 5.699
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.70".fwhm]
val = 0.153
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_5.87".wave]
val = 5.856
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.87".fwhm]
val = 0.119
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_6.00".wave]
val = 6.019
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.00".fwhm]
val = 0.085
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_6.21"]
complex = "6.2"

[dust_features."PAH_6.21".wave]
val = 6.214
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.21".fwhm]
val = 0.105
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_6.33"]
complex = "6.2"

[dust_features."PAH_6.33".wave]
val = 6.329
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.33".fwhm]
val = 0.206
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_6.70".wave]
val = 6.705
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.70".fwhm]
val = 0.515
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_7.42"]
complex = "7.7"

[dust_features."PAH_7.42".wave]
val = 7.427
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.42".fwhm]
val = 0.942
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_7.60"]
complex = "7.7"

[dust_features."PAH_7.60".wave]
val = 7.587
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.60".fwhm]
val = 0.249
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_7.84"]
complex = "7.7"

[dust_features."PAH_7.84".wave]
val = 7.841
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.84".fwhm]
val = 0.432
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_8.29".wave]
val = 8.293
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.29".fwhm]
val = 0.423
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_8.60".wave]
val = 8.602
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.60".fwhm]
val = 0.296
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_10.63".wave]
val = 10.630
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_10.63".fwhm]
val = 0.229
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_11.00".wave]
val = 10.978
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.00".fwhm]
val = 0.063
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_11.15"]
complex = "11.3"

[dust_features."PAH_11.15".wave]
val = 11.191
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.15".fwhm]
val = 0.023
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_11.21"]
complex = "11.3"

[dust_features."PAH_11.21".wave]
val = 11.211
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.21".fwhm]
val = 0.028
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_11.24"]
complex = "11.3"

[dust_features."PAH_11.24".wave]
val = 11.244
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.24".fwhm]
val = 0.043
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_11.29"]
complex = "11.3"

[dust_features."PAH_11.29".wave]
val = 11.291
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.29".fwhm]
val = 0.077
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_11.38"]
complex = "11.3"

[dust_features."PAH_11.38".wave]
val = 11.380
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.38".fwhm]
val = 0.362
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_11.95".wave]
val = 11.956
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.95".fwhm]
val = 0.594
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_12.63".wave]
val = 12.635
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.63".fwhm]
val = 0.573
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_12.74".wave]
val = 12.738
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.74".fwhm]
val = 0.111
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_13.44".wave]
val = 13.439
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_13.44".fwhm]
val = 0.593
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_13.99".wave]
val = 13.99
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_13.99".fwhm]
val = 0.248
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_14.21".wave]
val = 14.207
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_14.21".fwhm]
val = 0.390
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_14.64".wave]
val = 14.639
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_14.64".fwhm]
val = 0.384
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_15.85".wave]
val = 15.851
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_15.85".fwhm]
val = 0.276
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_16.45"]
complex = "17"

[dust_features."PAH_16.45".wave]
val = 16.459
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_16.45".fwhm]
val = 0.156
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_17.02"]
complex = "17"

[dust_features."PAH_17.02".wave]
val = 17.023
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.02".fwhm]
val = 0.877
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_17.39"]
complex = "17"

[dust_features."PAH_17.39".wave]
val = 17.389
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.39".fwhm]
val = 0.190
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_17.88"]
complex = "17"

[dust_features."PAH_17.88".wave]
val = 17.887
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.88".fwhm]
val = 0.258
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_18.94".wave]
val = 18.937
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_18.94".fwhm]
val = 0.395
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_33.10".wave]
val = 33.1
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_33.10".fwhm]
val = 1.655
plim = [0.9, 1.1]
locked = false

# Absorption features (modeled with gaussian profiles)

# Spectral leak artifact of the JWST pipeline at ~12.22 microns

# [absorption_features."abs_leak_12.22"]
# local = true

# [absorption_features."abs_leak_12.22".tau]
# val = 0.1
# plim = [0.0, 0.2]
# locked = false

# [absorption_features."abs_leak_12.22".wave]
# val = 12.22
# plim = [-0.1, 0.1]
# locked = true

# [absorption_features."abs_leak_12.22".fwhm]
# val = 0.133
# plim = [0.9, 1.1]
# locked = true

# Other potential absorption features:
# HCO+ @ 12.1 um
# C2H2 @ 13.7 um
# HCN  @ 14.0 um
# HNC  @ 21.7 um

# extinction.tau_9_7: the optical depth at 9.7 microns.
# Default: gets estimated by the continuum at 9.7 microns.
[extinction.tau_9_7]
val = 0.1
plim = [0.0, 3.0]
locked = false

# extinction.N_XXX: mass column densities (g/cm^2) for amorphous olivine, 
# amorphous pyroxene, and crystalline forsterite
# Note: these are only used if extinction_curve = "decompose"
[extinction.N_oli]
val = 1.7e-3
plim = [0.0, 3e-3]
locked = false

[extinction.N_pyr]
val = 5.0e-5
plim = [0.0, 3e-3]
locked = false

[extinction.N_for]
val = 1.0e-4
plim = [0.0, 3e-3]
locked = false

# extinction.frac: covering fraction for how much of the dust continuum
# (blackbodies and power laws) is affected by the extinction
[extinction.frac]
val = 1.0
plim = [0.5, 1.0]
locked = true
 
# extinction.tau_ice: *not* an actual optical depth -- this is
# a fraction of the CH optical depth that applies to the ice feature
[extinction.tau_ice]
val = 0.48
plim = [0.43, 0.53]
locked = true

# extinction.tau_ch: the optical depth from CH absorption
# at ~6.9 microns (the peak).
[extinction.tau_ch]
val = 0.0
plim = [0.0, 1.0]
locked = true

# extinction.beta: the mixing ratio for the extinction profile,
# between the profile specified in options.toml and a -1.7 index
# power law on the wavelength, relative to 9.7 microns.
[extinction.beta]
val = 0.1
plim = [0.0, 1.0]
locked = true

# Hot dust components
# Temperature, 800-1600 K
[hot_dust.temp]
val = 1200.0
plim = [800.0, 1600.0]
locked = false

# Covering fraction (0-1) of cold clouds
[hot_dust.frac]
val = 0.5
plim = [0.0, 1.0]
locked = false

# Optical depth of warm dust
[hot_dust.tau_warm]
val = 0.1
plim = [0.0, 100.0]
locked = false

# Optical depth of cold dust
[hot_dust.tau_cold]
val = 0.1
plim = [0.0, 100.0]
locked = false

# Peak location of 10 um silicate emission feature
[hot_dust.peak]
# val = 10.421
val = 10.0178
plim = [10.0, 10.8]
locked = true
