# dust.toml: This file contains options pertaining to fitting the 
# continuum model of spectra, including stellar & dust components.

# Each value has a "val" key which specifies the starting value,
# "plim" specifies the lower and upper limits on the parameter, and
# "locked" specifies whether the parameter should be fixed or allowed
# to vary during the fit.

# stellar_continuum_temp: the blackbody temperature of the stellar
# continuum component of the model. Default: 5000 K.
[stellar_continuum_temp]
val = 5000.0
plim = [4999.9, 5000.1]
locked = true

# dust_continuum_temps: the blackbody temperatures of the dust
# continuum components of the model. Defaults: 500, 300, 200, 135,
# 90, 65, 50, 40, and 35 K.
# [[dust_continuum_temps]]
# val = 50.0
# plim = [25.0, 1500.0]
# locked = false
# [[dust_continuum_temps]]
# val = 100.0
# plim = [25.0, 1500.0]
# locked = false
# [[dust_continuum_temps]]
# val = 300.0
# plim = [25.0, 1500.0]
# locked = false
# [[dust_continuum_temps]]
# val = 500.0
# plim = [25.0, 1500.0]
# locked = false

# [[dust_continuum_temps]]
# val = 35.0
# plim = [25.0, 50.0]
# locked = false
# [[dust_continuum_temps]]
# val = 75.0
# plim = [50.0, 150.0]
# locked = false
# [[dust_continuum_temps]]
# val = 300.0
# plim = [150.0, 500.0]
# locked = false
# [[dust_continuum_temps]]
# val = 1000.0
# plim = [500.0, 1500.0]
# locked = false

[[dust_continuum_temps]]
val = 1500.0
plim = [1499.9, 1500.1]
locked = true
[[dust_continuum_temps]]
val = 1000.0
plim = [999.9, 1000.1]
locked = true
[[dust_continuum_temps]]
val = 750.0
plim = [749.9, 750.1]
locked = true
[[dust_continuum_temps]]
val = 500.0
plim = [499.9, 500.1]
locked = true
[[dust_continuum_temps]]
val = 300.0
plim = [299.9, 300.1]
locked = true
[[dust_continuum_temps]]
val = 200.0
plim = [199.9, 200.1]
locked = true
[[dust_continuum_temps]]
val = 135.0
plim = [134.9, 135.1]
locked = true
[[dust_continuum_temps]]
val = 90.0
plim = [89.9, 90.1]
locked = true
[[dust_continuum_temps]]
val = 65.0
plim = [64.9, 65.1]
locked = true
[[dust_continuum_temps]]
val = 50.0
plim = [49.9, 50.1]
locked = true
[[dust_continuum_temps]]
val = 40.0
plim = [39.9, 40.1]
locked = true
[[dust_continuum_temps]]
val = 35.0
plim = [34.9, 35.1]
locked = true

# [[power_law_indices]]
# val = 0.0
# plim = [-3.0, 3.0]
# locked = false

# dust_features: each of these specifies a Polycyclic Aromatic 
# Hydrocarbon (PAH) profile to include in the model. Each of these
# profiles has an associated "wave", or central wavelength in microns,
# and "fwhm", or full-width at half-maximum, also in microns. They
# are modeled using Drude profiles.  The names should follow the
# general format of "PAH_X.XX", filling in X with the central wavelength
# up to 2 decimal places (or more if necessary).

[dust_features."PAH_3.29".wave]
val = 3.29
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_3.29".fwhm]
val = 0.060
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_5.24".wave]
val = 5.24
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.24".fwhm]
val = 0.058
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_5.27".wave]
val = 5.27
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.27".fwhm]
val = 0.179
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_5.70".wave]
val = 5.7
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.70".fwhm]
val = 0.200
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_5.87".wave]
val = 5.87
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.87".fwhm]
val = 0.200
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.00".wave]
val = 6.0
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.00".fwhm]
val = 0.198
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.18".wave]
val = 6.18
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.18".fwhm]
val = 0.05
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.20".wave]
val = 6.20
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.20".fwhm]
val = 0.07
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.22".wave]
val = 6.22
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.22".fwhm]
val = 0.114
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.30".wave]
val = 6.3
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.30".fwhm]
val = 0.189
plim = [0.4, 1.4]
locked = false

# [dust_features."PAH_6.44".wave]
# val = 6.44
# plim = [-0.05, 0.05]
# locked = false

# [dust_features."PAH_6.44".fwhm]
# val = 0.378
# plim = [0.4, 1.4]
# locked = false

[dust_features."PAH_6.69".wave]
val = 6.69
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.69".fwhm]
val = 0.468
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.42".wave]
val = 7.42
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.42".fwhm]
val = 0.935
plim = [0.4, 1.1]
locked = false

# [dust_features."PAH_7.60".wave]
# val = 7.60
# plim = [-0.05, 0.05]
# locked = false

# [dust_features."PAH_7.60".fwhm]
# val = 0.334
# plim = [0.4, 1.4]
# locked = false

[dust_features."PAH_7.52".wave]
val = 7.52
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.52".fwhm]
val = 0.226
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.62".wave]
val = 7.62
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.62".fwhm]
val = 0.152
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.75".wave]
val = 7.75
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.75".fwhm]
val = 0.160
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.85".wave]
val = 7.85
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.85".fwhm]
val = 0.152
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_8.00".wave]
val = 8.00
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.00".fwhm]
val = 0.285
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_8.31".wave]
val = 8.31
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.31".fwhm]
val = 0.206
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_8.33".wave]
val = 8.33
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.33".fwhm]
val = 0.417
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_8.61".wave]
val = 8.61
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.61".fwhm]
val = 0.336
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_10.68".wave]
val = 10.68
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_10.68".fwhm]
val = 0.214
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.00".wave]
val = 11.0
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.00".fwhm]
val = 0.099
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.15".wave]
val = 11.15
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.15".fwhm]
val = 0.033
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.20".wave]
val = 11.2
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.20".fwhm]
val = 0.034
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.22".wave]
val = 11.22
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.22".fwhm]
val = 0.101
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.25".wave]
val = 11.25
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.25".fwhm]
val = 0.135
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.33".wave]
val = 11.33
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.33".fwhm]
val = 0.363
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.95".wave]
val = 11.95
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.95".fwhm]
val = 0.300
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.00".wave]
val = 12.00
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.00".fwhm]
val = 0.700
plim = [0.4, 1.4]
locked = false

# [dust_features."PAH_11.99".wave]
# val = 11.99
# plim = [-0.05, 0.05]
# locked = false

# [dust_features."PAH_11.99".fwhm]
# val = 0.540
# plim = [0.4, 1.4]
# locked = false

[dust_features."PAH_12.50".wave]
val = 12.50
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.50".fwhm]
val = 0.505
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.60".wave]
val = 12.60
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.60".fwhm]
val = 0.300
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.69".wave]
val = 12.69
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.69".fwhm]
val = 0.165
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_13.48".wave]
val = 13.48
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_13.48".fwhm]
val = 0.539
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_14.04".wave]
val = 14.04
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_14.04".fwhm]
val = 0.225
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_14.19".wave]
val = 14.19
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_14.19".fwhm]
val = 0.355
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_14.65".wave]
val = 14.65
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_14.65".fwhm]
val = 0.498
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_15.90".wave]
val = 15.9
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_15.90".fwhm]
val = 0.318
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_16.45".wave]
val = 16.45
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_16.45".fwhm]
val = 0.230
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_17.04".wave]
val = 17.04
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.04".fwhm]
val = 1.108
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_17.375".wave]
val = 17.375
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.375".fwhm]
val = 0.209
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_17.87".wave]
val = 17.87
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.87".fwhm]
val = 0.286
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_18.92".wave]
val = 18.92
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_18.92".fwhm]
val = 0.359
plim = [0.4, 1.4]
locked = false

# ~19.8 um PAH feature? https://www.aanda.org/articles/aa/full_html/2010/03/aa12714-09/aa12714-09.html
# https://iopscience.iop.org/article/10.1088/0004-637X/712/1/69

[dust_features."PAH_33.10".wave]
val = 33.1
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_33.10".fwhm]
val = 1.655
plim = [0.4, 1.1]
locked = false


# extinction.tau_9_7: the optical depth at 9.7 microns.
# Default: gets estimated by the continuum at 9.7 microns.
[extinction.tau_9_7]
val = 0.1
plim = [0.0, 10.0]
locked = false

# extinction.tau_ice: the optical depth from ice absorption
# at ~6.9 microns (the peak).
[extinction.tau_ice]
val = 0.0
plim = [0.0, 10.0]
locked = true

# extinction.tau_ch: the optical depth from CH absorption
# at ~6.9 microns (the peak).
[extinction.tau_ch]
val = 0.0
plim = [0.0, 10.0]
locked = true

# extinction.beta: the mixing ratio for the extinction profile,
# between the profile specified in options.toml and a -1.7 index
# power law on the wavelength, relative to 9.7 microns.
[extinction.beta]
val = 0.1
plim = [0.0, 1.0]
locked = true


# Hot dust components
# Temperature, 800-1600 K
[hot_dust.temp]
val = 289.8
plim = [100.0, 1500.0]
locked = false

# Size, absolute limits: 0.001-10 microns
[hot_dust.size]
val = 1.5
plim = [0.8, 2.5]
locked = false

# Covering fraction (0-1) of cold clouds
[hot_dust.frac]
val = 0.0
plim = [0.0, 1.0]
locked = true

# Optical depth of warm dust
[hot_dust.tau_hot]
val = 0.0
plim = [0.0, 1000.0]
locked = true
