# dust.toml: This file contains options pertaining to fitting the 
# MIR continuum model of spectra, including stellar & dust components.

# Each value has a "val" key which specifies the starting value,
# "plim" specifies the lower and upper limits on the parameter, and
# "locked" specifies whether the parameter should be fixed or allowed
# to vary during the fit.

# stellar_continuum_temp: the blackbody temperature of the stellar
# continuum component of the model. Default: 5000 K.
[stellar_continuum_temp]
val = 5000.0
plim = [4999.9, 5000.1]
locked = true

# dust_continuum_temps: the blackbody temperatures of the dust
# continuum components of the model. Defaults: 300, 200, 135,
# 90, 65, 50, 40, and 35 K.
[[dust_continuum_temps]]
val = 500.0
plim = [499.9, 500.1]
locked = true
[[dust_continuum_temps]]
val = 300.0
plim = [299.9, 300.1]
locked = true
[[dust_continuum_temps]]
val = 200.0
plim = [199.9, 200.1]
locked = true
[[dust_continuum_temps]]
val = 135.0
plim = [134.9, 135.1]
locked = true
[[dust_continuum_temps]]
val = 90.0
plim = [89.9, 90.1]
locked = true
[[dust_continuum_temps]]
val = 65.0
plim = [64.9, 65.1]
locked = true
[[dust_continuum_temps]]
val = 50.0
plim = [49.9, 50.1]
locked = true
[[dust_continuum_temps]]
val = 40.0
plim = [39.9, 40.1]
locked = true
[[dust_continuum_temps]]
val = 35.0
plim = [34.9, 35.1]
locked = true

# [[power_law_indices]]
# val = 1.55
# plim = [-3.0, 3.0]
# locked = false

# dust_features: each of these specifies a Polycyclic Aromatic 
# Hydrocarbon (PAH) profile to include in the model. Each of these
# profiles has an associated "wave", or central wavelength in microns,
# and "fwhm", or full-width at half-maximum, also in microns. They
# are modeled using Drude profiles.  The names should follow the
# general format of "PAH_X.XX", filling in X with the central wavelength
# up to 2 decimal places (or more if necessary).

[dust_features."PAH_3.29".wave]
val = 3.29
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_3.29".fwhm]
val = 0.050
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_5.24".wave]
val = 5.24
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.24".fwhm]
val = 0.058
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_5.27".wave]
val = 5.27
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.27".fwhm]
val = 0.179
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_5.70".wave]
val = 5.7
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.70".fwhm]
val = 0.200
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_5.87".wave]
val = 5.87
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_5.87".fwhm]
val = 0.200
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.00".wave]
val = 6.0
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.00".fwhm]
val = 0.198
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.18"]
complex = "6.2"

[dust_features."PAH_6.18".wave]
val = 6.18
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.18".fwhm]
val = 0.05
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.20"]
complex = "6.2"

[dust_features."PAH_6.20".wave]
val = 6.20
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.20".fwhm]
val = 0.07
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.22"]
complex = "6.2"

[dust_features."PAH_6.22".wave]
val = 6.22
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.22".fwhm]
val = 0.114
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.30"]
complex = "6.2"

[dust_features."PAH_6.30".wave]
val = 6.3
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.30".fwhm]
val = 0.189
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_6.69".wave]
val = 6.69
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_6.69".fwhm]
val = 0.468
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.42"]
complex = "7.7"

[dust_features."PAH_7.42".wave]
val = 7.42
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.42".fwhm]
val = 0.935
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_7.43"]
complex = "7.7"

[dust_features."PAH_7.43".wave]
val = 7.43
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.43".fwhm]
val = 0.126
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.53"]
complex = "7.7"

[dust_features."PAH_7.53".wave]
val = 7.53
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.53".fwhm]
val = 0.136
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.60"]
complex = "7.7"

[dust_features."PAH_7.60".wave]
val = 7.60
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.60".fwhm]
val = 0.334
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.75"]
complex = "7.7"

[dust_features."PAH_7.75".wave]
val = 7.75
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.75".fwhm]
val = 0.113
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.85"]
complex = "7.7"

[dust_features."PAH_7.85".wave]
val = 7.85
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.85".fwhm]
val = 0.175
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_7.96"]
complex = "7.7"

[dust_features."PAH_7.96".wave]
val = 7.96
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_7.96".fwhm]
val = 0.283
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_8.31".wave]
val = 8.31
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.31".fwhm]
val = 0.080
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_8.33".wave]
val = 8.33
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.33".fwhm]
val = 0.417
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_8.61".wave]
val = 8.61
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.61".fwhm]
val = 0.272
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_8.76".wave]
val = 8.76
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_8.76".fwhm]
val = 0.470
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_10.60".wave]
val = 10.60
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_10.60".fwhm]
val = 0.214
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_10.75".wave]
val = 10.75
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_10.75".fwhm]
val = 0.100
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.00".wave]
val = 11.0
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.00".fwhm]
val = 0.099
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.15"]
complex = "11.3"

[dust_features."PAH_11.15".wave]
val = 11.15
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.15".fwhm]
val = 0.033
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.20"]
complex = "11.3"

[dust_features."PAH_11.20".wave]
val = 11.2
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.20".fwhm]
val = 0.034
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.22"]
complex = "11.3"

[dust_features."PAH_11.22".wave]
val = 11.22
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.22".fwhm]
val = 0.101
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.25"]
complex = "11.3"

[dust_features."PAH_11.25".wave]
val = 11.25
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.25".fwhm]
val = 0.135
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.33"]
complex = "11.3"

[dust_features."PAH_11.33".wave]
val = 11.33
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.33".fwhm]
val = 0.363
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.59"]
complex = "11.3"

[dust_features."PAH_11.59".wave]
val = 11.59
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.59".fwhm]
val = 0.125
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_11.99".wave]
val = 11.99
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_11.99".fwhm]
val = 0.540
plim = [0.4, 1.4]
locked = false

# [dust_features."PAH_12.62".wave]
# val = 12.62
# plim = [-0.05, 0.05]
# locked = false

# [dust_features."PAH_12.62".fwhm]
# val = 0.530
# plim = [0.4, 1.4]
# locked = false

# [dust_features."PAH_12.69".wave]
# val = 12.69
# plim = [-0.05, 0.05]
# locked = false

# [dust_features."PAH_12.69".fwhm]
# val = 0.165
# plim = [0.4, 1.4]
# locked = false

[dust_features."PAH_12.13".wave]
val = 12.13
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.13".fwhm]
val = 0.090
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.29"]
complex = "12.7"

[dust_features."PAH_12.29".wave]
val = 12.29
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.29".fwhm]
val = 0.192
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.40"]
complex = "12.7"

[dust_features."PAH_12.40".wave]
val = 12.40
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.40".fwhm]
val = 0.192
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.51"]
complex = "12.7"

[dust_features."PAH_12.51".wave]
val = 12.51
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.51".fwhm]
val = 0.170
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.61"]
complex = "12.7"

[dust_features."PAH_12.61".wave]
val = 12.61
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.61".fwhm]
val = 0.166
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.72"]
complex = "12.7"

[dust_features."PAH_12.72".wave]
val = 12.72
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.72".fwhm]
val = 0.146
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_12.80"]
complex = "12.7"

[dust_features."PAH_12.80".wave]
val = 12.80
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_12.80".fwhm]
val = 0.129
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_13.00"]
complex = "12.7"

[dust_features."PAH_13.00".wave]
val = 13.0
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_13.00".fwhm]
val = 0.789
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_13.48".wave]
val = 13.48
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_13.48".fwhm]
val = 0.539
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_14.04".wave]
val = 14.04
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_14.04".fwhm]
val = 0.225
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_14.19".wave]
val = 14.19
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_14.19".fwhm]
val = 0.355
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_14.65".wave]
val = 14.65
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_14.65".fwhm]
val = 0.498
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_15.90".wave]
val = 15.9
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_15.90".fwhm]
val = 0.318
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_16.45"]
complex = "17"

[dust_features."PAH_16.45".wave]
val = 16.45
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_16.45".fwhm]
val = 0.230
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_17.04"]
complex = "17"

[dust_features."PAH_17.04".wave]
val = 17.04
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.04".fwhm]
val = 1.108
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_17.375"]
complex = "17"

[dust_features."PAH_17.375".wave]
val = 17.375
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.375".fwhm]
val = 0.209
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_17.87"]
complex = "17"

[dust_features."PAH_17.87".wave]
val = 17.87
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_17.87".fwhm]
val = 0.286
plim = [0.4, 1.4]
locked = false

[dust_features."PAH_18.92".wave]
val = 18.92
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_18.92".fwhm]
val = 0.359
plim = [0.4, 1.4]
locked = false

# ~19.8 um PAH feature? https://www.aanda.org/articles/aa/full_html/2010/03/aa12714-09/aa12714-09.html
# https://iopscience.iop.org/article/10.1088/0004-637X/712/1/69

[dust_features."PAH_33.10".wave]
val = 33.1
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_33.10".fwhm]
val = 1.655
plim = [0.4, 1.1]
locked = false

# Absorption features (also modeled with Drude profiles)

# Spectral leak artifact of the JWST pipeline at ~12.22 microns
# UPDATE: This has been fixed as of JWST pipeline version 1.11+

# [absorption_features."abs_leak_12.22"]
# local = true

# [absorption_features."abs_leak_12.22".tau]
# val = 0.1
# plim = [0.0, 0.2]
# locked = false

# [absorption_features."abs_leak_12.22".wave]
# val = 12.22
# plim = [-0.1, 0.1]
# locked = true

# [absorption_features."abs_leak_12.22".fwhm]
# val = 0.133
# plim = [0.4, 1.4]
# locked = true

# [absorption_features."abs_C2H2_13.7".wave]
# val = 13.69
# plim = [-0.1, 0.1]
# locked = true

# [absorption_features."abs_C2H2_13.7".fwhm]
# val = 0.0197
# plim = [0.4, 1.4]
# locked = true

# Other potential absorption features:
# HCO+ @ 12.1 um
# HCN  @ 14.0 um
# HNC  @ 21.7 um

# extinction.tau_9_7: the optical depth at 9.7 microns.
# Default: gets estimated by the continuum at 9.7 microns.
[extinction.tau_9_7]
val = 0.1
plim = [0.0, 100.0]
locked = false

# extinction.tau_ice: *not* an actual optical depth -- this is
# a fraction of the CH optical depth that applies to the ice feature
[extinction.tau_ice]
val = 0.48
plim = [0.43, 0.53]
locked = true

# extinction.tau_ch: the optical depth from CH absorption
# at ~6.9 microns (the peak).
[extinction.tau_ch]
val = 0.1
plim = [0.0, 10.0]
locked = false

# extinction.beta: the mixing ratio for the extinction profile,
# between the profile specified in options.toml and a -1.7 index
# power law on the wavelength, relative to 9.7 microns.
[extinction.beta]
val = 0.1
plim = [0.0, 1.0]
locked = true


# Hot dust components
# Temperature, 800-1600 K
[hot_dust.temp]
val = 1200.0
plim = [800.0, 1600.0]
locked = false

# Covering fraction (0-1) of cold clouds
[hot_dust.frac]
val = 0.5
plim = [0.0, 1.0]
locked = false

# Optical depth of warm dust
[hot_dust.tau_warm]
val = 0.1
plim = [0.0, 100.0]
locked = false

# Optical depth of cold dust
[hot_dust.tau_cold]
val = 0.1
plim = [0.0, 100.0]
locked = false

# Peak location of 10 um silicate emission feature
[hot_dust.peak]
# val = 10.421
val = 10.0178
plim = [10.0, 10.8]
locked = true
