# dust.toml: This file contains options pertaining to fitting the 
# MIR continuum model of spectra, including stellar & dust components.

# Each value has a "val" key which specifies the starting value,
# "plim" specifies the lower and upper limits on the parameter, and
# "locked" specifies whether the parameter should be fixed or allowed
# to vary during the fit.

# dust_continuum_temps: the blackbody temperatures of the dust
# continuum components of the model. 
[[dust_continuum_temps]]
val = 400.0
plim = [35.0, 1500.0]
locked = false
[[dust_continuum_temps]]
val = 300.0
plim = [35.0, 300.0]
locked = false
[[dust_continuum_temps]]
val = 100.0
plim = [35.0, 300.0]
locked = false
[[dust_continuum_temps]]
val = 40.0
plim = [35.0, 300.0]
locked = false

# PAHFIT Model: A series of profiles at fixed temperatures b/w 35-500 K
# [[dust_continuum_temps]]
# val = 400.0
# plim = [399.9, 400.1]
# locked = true
# [[dust_continuum_temps]]
# val = 300.0
# plim = [299.9, 300.1]
# locked = true
# [[dust_continuum_temps]]
# val = 200.0
# plim = [199.9, 200.1]
# locked = true
# [[dust_continuum_temps]]
# val = 135.0
# plim = [134.9, 135.1]
# locked = true
# [[dust_continuum_temps]]
# val = 90.0
# plim = [89.9, 90.1]
# locked = true
# [[dust_continuum_temps]]
# val = 65.0
# plim = [64.9, 65.1]
# locked = true
# [[dust_continuum_temps]]
# val = 50.0
# plim = [49.9, 50.1]
# locked = true
# [[dust_continuum_temps]]
# val = 40.0
# plim = [39.9, 40.1]
# locked = true
# [[dust_continuum_temps]]
# val = 35.0
# plim = [34.9, 35.1]
# locked = true

# power laws: should not be used in conjunction with blackbodies 
# (should be one or the other) since they are degenerate.
# [[power_law_indices]]
# val = 1.65
# plim = [-3.0, 3.0]
# locked = true

# template_amps: amplitude parameters for each template in the fit
# do NOT repeat entries here for different subchannel amplitudes -- those are handled internally
# and the initial value/limits/locked are assumed to be the same for each subchannel amplitude for a given
# template
# ONLY APPLIES if the fit_temp_multexp option is disabled
[[template_amps]]
val = 1.0
plim = [0.5, 1.5]
locked = false

# template_inds: exponential indices on templates - ONLY APPLIES if the fit_temp_multexp option is enabled
# i.e. these are mutually exclusive with [[template_amps]]
[[template_inds]]
val = 0.0
plim = [0.0, inf]
locked = false
[[template_inds]]
val = 0.0
plim = [0.0, inf]
locked = false
[[template_inds]]
val = 0.0
plim = [0.0, inf]
locked = false
[[template_inds]]
val = 0.0
plim = [0.0, inf]
locked = false

# dust_features: each of these specifies a Polycyclic Aromatic 
# Hydrocarbon (PAH) profile to include in the model. Each of these
# profiles has an associated "wave", or central wavelength in microns,
# and "fwhm", or full-width at half-maximum, also in microns. They
# are modeled using Drude profiles.  The names should follow the
# general format of "PAH_XXX", filling in X with the central wavelength
# up to 2 decimal places. Filling only 2 decimal places allows the
# naming scheme to be consistent without having to mark the decimal place
# itself within the name, which can cause problems with parsing.

[dust_features."PAH_329".wave]
val = 3.29
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_329".fwhm]
val = 0.04
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_329".asym]
val = 0.52
plim = [0.5, 1.5]
locked = false

[dust_features."PAH_340".wave]
val = 3.40
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_340".fwhm]
val = 0.03
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_340".asym]
val = -10.0
plim = [1.5, 0.5]
locked = false

[dust_features."PAH_347".wave]
val = 3.47
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_347".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_347".asym]
val = -0.80
plim = [1.5, 0.5]
locked = false

[dust_features."PAH_518"]
complex = "PAH_520"

[dust_features."PAH_518".wave]
val = 5.18
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_518".fwhm]
val = 0.05
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_524"]
complex = "PAH_520"

[dust_features."PAH_524".wave]
val = 5.24
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_524".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_524".asym]
val = -3.00
plim = [1.5, 0.5]
locked = false

[dust_features."PAH_545".wave]
val = 5.45
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_545".fwhm]
val = 0.15
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_553".wave]
val = 5.53
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_553".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_564"]
complex = "PAH_570"

[dust_features."PAH_564".wave]
val = 5.64
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_564".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_571"]
complex = "PAH_570"

[dust_features."PAH_571".wave]
val = 5.70
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_571".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_576"]
complex = "PAH_570"

[dust_features."PAH_576".wave]
val = 5.76
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_576".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_587".wave]
val = 5.87
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_587".fwhm]
val = 0.15
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_600".wave]
val = 6.00
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_600".fwhm]
val = 0.20
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_620".wave]
val = 6.20
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_620".fwhm]
val = 0.15
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_620".asym]
val = -6.00
plim = [1.5, 0.5]
locked = false

[dust_features."PAH_670".wave]
val = 6.69
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_670".fwhm]
val = 0.40
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_710".wave]
val = 7.10
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_710".fwhm]
val = 0.40
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_742"]
complex = "PAH_770"

[dust_features."PAH_742".wave]
val = 7.42
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_742".fwhm]
val = 0.94
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_755"]
complex = "PAH_770"

[dust_features."PAH_755".wave]
val = 7.55
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_755".fwhm]
val = 0.30
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_761"]
complex = "PAH_770"

[dust_features."PAH_761".wave]
val = 7.61
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_761".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_782"]
complex = "PAH_770"

[dust_features."PAH_782".wave]
val = 7.82
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_782".fwhm]
val = 0.40
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_833".wave]
val = 8.33
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_833".fwhm]
val = 0.20
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_850"]
complex = "PAH_860"

[dust_features."PAH_850".wave]
val = 8.50
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_850".fwhm]
val = 0.20
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_861"]
complex = "PAH_860"

[dust_features."PAH_861".wave]
val = 8.61
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_861".fwhm]
val = 0.34
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1060".wave]
val = 10.60
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1060".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1074".wave]
val = 10.74
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1074".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1100".wave]
val = 11.00
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1100".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1100".asym]
val = -1.10
plim = [1.5, 0.5]
locked = false

[dust_features."PAH_1120"]
complex = "PAH_1130"

[dust_features."PAH_1120".wave]
val = 11.20
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1120".fwhm]
val = 0.10
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1126"]
complex = "PAH_1130"

[dust_features."PAH_1126".wave]
val = 11.26
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1126".fwhm]
val = 0.30
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1126".asym]
val = -10.0
plim = [1.5, 0.5]
locked = false

[dust_features."PAH_1199".wave]
val = 11.99
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1199".fwhm]
val = 0.54
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1260"]
complex = "PAH_1270"

[dust_features."PAH_1260".wave]
val = 12.60
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1260".fwhm]
val = 0.50
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1277"]
complex = "PAH_1270"

[dust_features."PAH_1277".wave]
val = 12.77
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1277".fwhm]
val = 0.15
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1315".wave]
val = 13.15
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1315".fwhm]
val = 0.50
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1355".wave]
val = 13.55
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1355".fwhm]
val = 0.20
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1355".asym]
val = -5.00
plim = [1.5, 0.5]
locked = false

[dust_features."PAH_1404".wave]
val = 14.04
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1404".fwhm]
val = 0.20
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1419".wave]
val = 14.19
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1419".fwhm]
val = 0.20
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1419".asym]
val = -5.00
plim = [1.5, 0.5]
locked = false

[dust_features."PAH_1590".wave]
val = 15.90
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1590".fwhm]
val = 0.32
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1645"]
complex = "PAH_1700"

[dust_features."PAH_1645".wave]
val = 16.45
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1645".fwhm]
val = 0.23
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1704"]
complex = "PAH_1700"

[dust_features."PAH_1704".wave]
val = 17.04
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1704".fwhm]
val = 1.11
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1738"]
complex = "PAH_1700"

[dust_features."PAH_1738".wave]
val = 17.38
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1738".fwhm]
val = 0.21
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1788"]
complex = "PAH_1700"

[dust_features."PAH_1788".wave]
val = 17.887
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1788".fwhm]
val = 0.258
plim = [0.4, 1.1]
locked = false

[dust_features."PAH_1894".wave]
val = 18.937
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_1894".fwhm]
val = 0.395
plim = [0.9, 1.1]
locked = false

[dust_features."PAH_3310".wave]
val = 33.1
plim = [-0.05, 0.05]
locked = false

[dust_features."PAH_3310".fwhm]
val = 1.655
plim = [0.4, 1.1]
locked = false

# Absorption features (modeled with gaussian profiles)

# Spectral leak artifact of the JWST pipeline at ~12.22 microns

# [absorption_features."abs_leak_1222".tau]
# val = 0.1
# plim = [0.0, 0.2]
# locked = false

# [absorption_features."abs_leak_1222".wave]
# val = 12.22
# plim = [-0.1, 0.1]
# locked = true

# [absorption_features."abs_leak_1222".fwhm]
# val = 0.133
# plim = [0.9, 1.1]
# locked = true

# Other potential absorption features:
# HCO+ @ 12.1 um
# C2H2 @ 13.7 um
# HCN  @ 14.0 um
# HNC  @ 21.7 um

# extinction.tau_9_7: the optical depth at 9.7 microns.
# Default: gets estimated by the continuum at 9.7 microns.
[extinction.tau_9_7]
val = 0.1
plim = [0.0, 10.0]
locked = false

# extinction.N_XXX: mass column densities (g/cm^2) for amorphous olivine, 
# amorphous pyroxene, and crystalline forsterite
# Note: these are only used if extinction_curve = "decompose"
[extinction.N_oli]
val = 1.7e-3
plim = [0.0, 3e-3]
locked = false

# pyr and for are measured RELATIVE to olivine (multiplicatively)
[extinction.N_pyr]
val = 0.03
plim = [0.0, 3.0]
locked = false

[extinction.N_for]
val = 0.06
plim = [0.0, 3.0]
locked = false

# extinction.tau_ice: *not* an actual optical depth -- this is
# a fraction of the CH optical depth that applies to the ice feature
[extinction.tau_ice]
val = 0.48
plim = [0.43, 0.53]
locked = true

# extinction.tau_ch: the optical depth from CH absorption
# at ~6.9 microns (the peak).
[extinction.tau_ch]
val = 0.0
plim = [0.0, 1.0]
locked = true

# extinction.beta: the mixing ratio for the extinction profile,
# between the profile specified in options.toml and a -1.7 index
# power law on the wavelength, relative to 9.7 microns.
[extinction.beta]
val = 0.1
plim = [0.0, 1.0]
locked = true

# Hot dust components
# Temperature, 800-1600 K
[hot_dust.temp]
val = 1200.0
plim = [800.0, 1600.0]
locked = false

# Covering fraction (0-1) of cold clouds
[hot_dust.frac]
val = 0.5
plim = [0.0, 1.0]
locked = false

# Optical depth of warm dust
[hot_dust.tau_warm]
val = 0.1
plim = [0.0, 100.0]
locked = false

# Optical depth of cold dust
[hot_dust.tau_cold]
val = 0.1
plim = [0.0, 100.0]
locked = false

# Peak location of 10 um silicate emission feature
# Dont edit this - it's unphysical!
[hot_dust.peak]
val = 10.0178
plim = [10.0, 10.8]
locked = true
