# lines.toml: This file contains options pertaining to the
# line model of the spectra.

# Tying parameters
tie_voigt_mixing = true     # tie the Voigt mixing ratios of all lines

# Kinematics groups: for each group, every line in the group will have a tied voff and fwhm, just specify which
#                    lines you want in each group

# kinematic_group_H2 = [
#     "H200_"
# ]

# kinematic_group_HI = [
#    "HI_"
# ]

# kinematic_group_low = [
#     "ArII_",
#     "ArIII_",
#     "FeII_",
#     "ClII_",
#     "FeIII_",
#     "HeII_",
#     "NeII_",
#     "NiII_",
#     "PIII_",
#     "SIII_"
# ]

# kinematic_group_med = [
#     "ArV_",
#     "NaIII_",
#     "NeIII_",
#     "OIV_",
#     "SIV_"
# ]

# kinematic_group_high = [
#     "FeVII_",
#     "FeVIII_",
#     "MgV_",
#     "MgVII_",
#     "NeV_",
#     "NeVI_",
# ]

kinematic_group_OIII = [
    "OIII_"
]
kinematic_group_OII = [
    "OII_"
]
kinematic_group_Balmer = [
    "HI_H_"
]
kinematic_group_He = [
    "HeI_",
    "HeII_"
]

# Line voff and FWHM limits
voff_plim = [-500.0, 500.0]              # -500 to 500 km/s from the rest wavelength
fwhm_plim = [0.0, 1000.0]                # 0 to 1000 km/s FWHM velocity of the line -- this is the *intrinsic* FWHM,
                                         #    i.e. the FWHM after the instrumental FWHM has been subtracted in quadrature
h3_plim = [-0.5, 0.5]                    # skewness (3rd moment): limits (-0.5, 0.5), to remain mostly gaussian
h4_plim = [-0.5, 0.5]                    # kurtosis (4th moment): limits (-0.5, 0.5), to remain mostly gaussian
eta_plim = [0.0, 1.0]                    # mixing parameter for Voigt profiles: limits (0.0, 1.0)

# Additional line components
n_acomps = 1
acomp_amp_plim = [[0.0, 1.0]]
acomp_voff_plim = [[-500.0, 500.0]]      # additive factor with the main line voff -> i.e. the additional component
                                         # is allowed to have a voff up to +/-500 km/s from the main component 
acomp_fwhm_plim = [[1.0, 5.0]]           # multiplicative factor with the main line FWHM -> i.e. the additional component
                                         # is allowed to have a FWHM from 1-5x the main component (it must be wider)

# Uncertainty in the wavelength solution of the data
flexible_wavesol = false                 # allow tied voffs to vary slightly based on wavelength solution uncertainty
wavesol_unc = 30.0                       # wavelength solution uncertainties in each of the 4 MIRI channels (<30 km/s)

# [channels]
# 1 = [4.9, 7.65]
# 2 = [7.51, 11.71]
# 3 = [11.55, 18.02]
# 4 = [17.71, 28.1]

# Central wavelengths of each line that should be included in the model, in microns
# Line wavelengths should be *vacuum* wavelengths, not air wavelengths

# Optical Sources:
#   Good general line list for common galaxy emission lines: http://astronomy.nmsu.edu/drewski/tableofemissionlines.html
#    * note: this source has lines in AIR wavelengths for lines above 2000 angstroms, so they must be converted to vacuum wavelengths.

# MIR Sources:
#   Good infrared line lists for HI, H2 and common ions: https://www.mpe.mpg.de/ir/ISO/linelists/
#   Good infrared line lists for HI and H2: https://www.not.iac.es/instruments/notcam/ReferenceInfo/
#   NIST: https://physics.nist.gov/PhysRefData/ASD/lines_form.html 


##################################### OPTICAL LINES ################################################

# Balmer Series (Hydrogen, n -> 2) lines
[lines.HI_H_alpha]
wave = 0.6564632
latex = "H$\\alpha$"
annotate = true

[lines.HI_H_beta]
wave = 0.4862691
latex = "H$\\beta$"
annotate = true

[lines.HI_H_gamma]
wave = 0.4341691
latex = "H$\\gamma$"
annotate = true

[lines.HI_H_delta]
wave = 0.4102900
latex = "H$\\delta$"
annotate = true

[lines.HI_H_epsilon]
wave = 0.3971202
latex = "H$\\varepsilon$"
annotate = true

[lines.HI_H_zeta]
wave = 0.3890166
latex = "H$\\zeta$"
annotate = true

# Helium lines
[lines.HeI_03889]
wave = 0.3889749
latex = "He I"
annotate = true

[lines.HeII_04687]
wave = 0.4687021
latex = "He II"
annotate = true

# [lines.HeI_05877]
# wave = 0.5877253
# latex = "He I"
# annotate = true

# [lines.HeI_07067]
# wave = 0.7067144
# latex = "He I"
# annotate = true

# Neon lines

# [Ne V] doublet
[lines.NeV_03346]
wave = 0.3346783
latex = "[Ne V]"
annotate = true

[lines.NeV_03426]
wave = 0.3426863
latex = "[Ne V]"
annotate = true

[lines.NeIII_03869]
wave = 0.3869856
latex = "[Ne III]"
annotate = true

[lines.NeIII_03967]
wave = 0.3968593
latex = "[Ne III]"
annotate = true

# Oxygen lines

[lines.OIII_03445]
wave = 0.3445039
latex = "O III"
annotate = true

# [O II] doublet
[lines.OII_03727]
wave = 0.3727092
latex = "[O II]"
annotate = true

[lines.OII_03729]
wave = 0.3729875
latex = "[O II]"
annotate = true

[lines.OIII_04364]
wave = 0.4364436
latex = "[O III]"
annotate = true

# [O III] doublet
[lines.OIII_04960]
wave = 0.4960295
latex = "[O III]"
annotate = true

[lines.OIII_05008]
wave = 0.5008240
latex = "[O III]"
annotate = true

[lines.OI_06302]
wave = 0.6302046
latex = "[O I]"
annotate = true

[lines.OI_06366]
wave = 0.6365535
latex = "[O I]"
annotate = true

[lines.OII_07322]
wave = 0.7322007
latex = "[O II]"
annotate = true

[lines.OII_07333]
wave = 0.7332750
latex = "[O II]"
annotate = true

# Iron lines
# [lines.FeXIV_05304]
# wave = 0.5304335
# latex = "[Fe XIV]"
# annotate = true

# [lines.FeVI_05639]
# wave = 0.5639165
# latex = "[Fe VI]"
# annotate = true

# [lines.FeVI_05679]
# wave = 0.5678575
# latex = "[Fe VI]"
# annotate = true

# [lines.FeVII_05722]
# wave = 0.5722287
# latex = "[Fe VII]"
# annotate = true

# [lines.FeVII_06088]
# wave = 0.6088685
# latex = "[Fe VII]"
# annotate = true

[lines.FeX_06374]
wave = 0.6376272
latex = "[Fe X]"
annotate = true

[lines.FeXI_07894]
wave = 0.7893971
latex = "[Fe XI]"
annotate = true

# Sulfur lines
[lines.SIII_06314]
wave = 0.6313806
latex = "[S III]"
annotate = true

[lines.SII_06718]
wave = 0.6718294
latex = "[S II]"
annotate = true

[lines.SII_06733]
wave = 0.6732668
latex = "[S II]"
annotate = true

# Nitrogen lines
[lines.NII_06550]
wave = 0.6549859
latex = "[N II]"
annotate = true

[lines.NII_06585]
wave = 0.6585279
latex = "[N II]"
annotate = true

# Argon lines
[lines.ArIII_07138]
wave = 0.7137757
latex = "[Ar III]"
annotate = true

# Nickel lines
[lines.NiIII_07892]
wave = 0.7892071
latex = "[Ni III]"
annotate = true

####################################### MIR LINES ##################################################

# Brackett Series (Hydrogen, n -> 4) Lines
[lines.HI_Br_alpha]
wave = 4.05225
latex = "Br$\\alpha$"
annotate = false

[lines.HI_Br_beta]
wave = 2.6259
latex = "Br$\\beta$"
annotate = false

[lines.HI_Br_gamma]
wave = 2.1661
latex = "Br$\\gamma$"
annotate = false

# Pfund Series (Hydrogen, n -> 5) Lines
[lines.HI_Pf_alpha]
wave = 7.4599
latex = "Pf$\\alpha$"
annotate = false

[lines.HI_Pf_beta]
wave = 4.6538
latex = "Pf$\\beta$"
annotate = false

[lines.HI_Pf_gamma]
wave = 3.7405
latex = "Pf$\\gamma$"
annotate = false

[lines.HI_Pf_delta]
wave = 3.2970
latex = "Pf$\\delta$"
annotate = false

[lines.HI_Pf_epsilon]
wave = 3.0392
latex = "Pf$\\varepsilon$"
annotate = false

# Humphreys Series (Hydrogen, n -> 6) Lines
[lines.HI_Hu_alpha]
wave = 12.372
latex = "Hu$\\alpha$"
annotate = false

[lines.HI_Hu_beta]
wave = 7.503
latex = "Hu$\\beta$"
annotate = false

[lines.HI_Hu_gamma]
wave = 5.908
latex = "Hu$\\gamma$"
annotate = false

[lines.HI_Hu_delta]
wave = 5.129
latex = "Hu$\\delta$"
annotate = false

[lines.HI_Hu_epsilon]
wave = 4.673
latex = "Hu$\\varepsilon$"
annotate = false

# Argon Lines
[lines.ArII_6985]
wave = 6.985274
latex = "[Ar II]"
annotate = true

[lines.ArV_7901]
wave = 7.901600
latex = "[Ar V]"
annotate = false

[lines.ArIII_8991]
wave = 8.991380
latex = "[Ar III]"
annotate = true

[lines.ArV_13102]
wave = 13.102200
latex = "[Ar V]"
annotate = true

# Chlorine Lines
[lines.ClII_14368]
wave = 14.367800
latex = "[Cl II]"
annotate = false

# Iron Lines
[lines.FeII_4889]
wave = 4.889137
latex = "[Fe II]"
annotate = false

[lines.FeII_5062]
wave = 5.062350
latex = "[Fe II]"
annotate = false

[lines.FeII_5340]
wave = 5.340169
latex = "[Fe II]"
annotate = true

[lines.FeVIII_5447]
wave = 5.4466
latex = "[Fe VIII]"
annotate = false

[lines.FeII_6721]
wave = 6.721283
latex = "[Fe II]"
annotate = false

[lines.FeVII_7814]
wave = 7.814500
latex = "[Fe VII]"
annotate = false

[lines.FeVII_9527]
wave = 9.526700
latex = "[Fe VII]"
annotate = false

[lines.FeII_17936]
wave = 17.935950
latex = "[Fe II]"
annotate = false

[lines.FeIII_22925]
wave = 22.925000
latex = "[Fe III]"
annotate = false

[lines.FeII_25988]
wave = 25.988290
latex = "[Fe II]"
annotate = false

# Helium Lines
[lines.HeII_5228]
wave = 5.2279972
latex = "He II"
annotate = false

# Magnesium Lines
[lines.MgVII_5503]
wave = 5.503200
latex = "[Mg VII]"
annotate = false

[lines.MgV_5609]
wave = 5.609850
latex = "[Mg V]"
annotate = true

[lines.MgV_13521]
wave = 13.521300
latex = "[Mg V]"
annotate = false

# Sodium Lines
[lines.NaIII_7318]
wave = 7.317700
latex = "[Na III]"
annotate = false

# Neon Lines
[lines.NeVI_7652]
wave = 7.652400
latex = "[Ne VI]"
annotate = true

[lines.NeII_12813]
wave = 12.813550
latex = "[Ne II]"
annotate = true

[lines.NeV_14322]
wave = 14.321700
latex = "[Ne V]"
annotate = true

[lines.NeIII_15555]
wave = 15.555100
latex = "[Ne III]"
annotate = true

[lines.NeV_24318]
wave = 24.317500
latex = "[Ne V]"
annotate = true

# Nickel Lines
[lines.NiII_6636]
wave = 6.636000
latex = "[Ni II]"
annotate = false

# Oxygen Lines
[lines.OIV_25890]
wave = 25.890300
latex = "[O IV]"
annotate = true

# Phosphorus Lines
[lines.PIII_17885]
wave = 17.885000
latex = "[P III]"
annotate = false

# Sulfur Lines
[lines.SIV_10511]
wave = 10.510500
latex = "[S IV]"
annotate = true

[lines.SIII_18713]
wave = 18.713000
latex = "[S III]"
annotate = true

# Molecular Hydrogen Lines
[lines.H200_S8]
wave = 5.05312
latex = "H$_2$ 0-0 $S(8)$"
annotate = true

[lines.H200_S7]
wave = 5.51118
latex = "H$_2$ 0-0 $S(7)$"
annotate = true

[lines.H200_S6]
wave = 6.10857
latex = "H$_2$ 0-0 $S(6)$"
annotate = true

[lines.H200_S5]
wave = 6.90952
latex = "H$_2$ 0-0 $S(5)$"
annotate = true

[lines.H200_S4]
wave = 8.02505
latex = "H$_2$ 0-0 $S(4)$"
annotate = true

[lines.H200_S3]
wave = 9.66492
latex = "H$_2$ 0-0 $S(3)$"
annotate = true

[lines.H200_S2]
wave = 12.27861
latex = "H$_2$ 0-0 $S(2)$"
annotate = true

[lines.H200_S1]
wave = 17.03484
latex = "H$_2$ 0-0 $S(1)$"
annotate = true

[lines.H200_S0]
wave = 28.21883
latex = "H$_2$ 0-0 $S(0)$"
annotate = true

# Other molecular Hydrogen lines (disabled):

# H200_S23   = 3.372
# H200_S22   = 3.366
# H200_S21   = 3.369
# H200_S20   = 3.380
# H200_S19   = 3.404
# H200_S18   = 3.438
# H200_S17   = 3.485
# H200_S16   = 3.547
# H200_S15   = 3.625
# H200_S14   = 3.724
# H200_S13   = 3.8464
# H200_S12   = 3.9947
# H200_S11   = 4.1810
# H200_S10   = 4.4096
# H200_S9    = 4.6947

# H298_Q9    = 5.00015
# H254_O7    = 5.00439
# H2119_O11  = 5.02342
# H287_O4    = 5.02511
# H287_Q13   = 5.02747
# H2109_Q3   = 5.04008
# H210_O10   = 5.05898
# H244_S12   = 5.08601
# H243_O8    = 5.09871
# H2109_Q4   = 5.11295
# H298_Q10   = 5.17014
# H298_O3    = 5.17942
# H2109_Q5   = 5.20735
# H21311_O5  = 5.22019
# H233_S10   = 5.22811
# H232_O9    = 5.23355
# H222_S9    = 5.23885
# H297_O16   = 5.25785
# H287_Q14   = 5.25982
# H255_S13   = 5.29119
# H244_S11   = 5.30128
# H2109_Q6   = 5.32590
# H211_S8    = 5.33014
# H2108_O14  = 5.36218
# H298_Q11   = 5.37265
# H221_O10   = 5.40991
# H276_O6    = 5.41544
# H265_O7    = 5.43289
# H21210_O9  = 5.44900
# H2109_O2   = 5.46232
# H255_S12   = 5.46376
# H287_O5    = 5.46773
# H2109_Q7   = 5.47218
# H254_O8    = 5.50790
# H287_Q15   = 5.54015
# H233_S9    = 5.55564
# H244_S10   = 5.57255
# H2119_O12  = 5.61351
# H298_O4    = 5.61372
# H298_Q12   = 5.61536
# H210_O11   = 5.62935
# H222_S8    = 5.63331
# H243_O9    = 5.63432
# H255_S11   = 5.68602
# H21311_O6  = 5.69839
# H266_S13   = 5.75527
# H21211_S5  = 5.78321
# H21211_S4  = 5.78514
# H21412_S1  = 5.80036
# H232_O10   = 5.80845
# H211_S7    = 5.81092
# H21211_S3  = 5.85980
# H21211_S6  = 5.86704
# H2109_Q9   = 5.87009
# H2109_O3   = 5.89588
# H298_Q13   = 5.90925
# H244_S9    = 5.91458
# H297_O17   = 5.91713
# H266_S12   = 5.92552
# H276_O7    = 5.95554
# H255_S10   = 5.96851
# H233_S8    = 5.96982
# H287_O6    = 5.99182
# H265_O8    = 5.99676
# H21211_S2  = 6.00227
# H221_O11   = 6.03194
# H21211_S7  = 6.06337
# H2108_O15  = 6.06954
# H254_O9    = 6.10291
# H298_O5    = 6.13039
# H21210_O10 = 6.13372
# H222_S7    = 6.13835
# H2109_Q10  = 6.13914
# H266_S11   = 6.15108
# H21211_S1  = 6.21316
# H243_O10   = 6.26916
# H298_Q14   = 6.27053
# H210_O12   = 6.30828
# H255_S9    = 6.32677
# H21311_O7  = 6.32694
# H244_S8    = 6.34892
# H277_S13   = 6.36635
# H2119_O13  = 6.39842
# H21110_O2  = 6.40152
# H2109_O4   = 6.41592
# H21211_S8  = 6.42531
# H211_S6    = 6.43835
# H266_S10   = 6.44265
# H21412_O2  = 6.46328
# H232_O11   = 6.49270
# H233_S7    = 6.50086
# H277_S12   = 6.51991
# H276_O8    = 6.59838
# H287_O7    = 6.61668
# H265_O9    = 6.66810
# H277_S11   = 6.73869
# H298_O6    = 6.74901
# H221_O12   = 6.77608
# H255_S8    = 6.78360
# H222_S6    = 6.79806
# H254_O10   = 6.81239
# H266_S9    = 6.81644
# H244_S7    = 6.90758
# H21412_O3  = 6.92886
# H21110_O3  = 6.94033
# H243_O11   = 7.02962
# H277_S10   = 7.03273
# H2108_O16  = 7.03407
# H2109_O5   = 7.04322
# H21210_O11 = 7.08920
# H210_O13   = 7.12548
# H21311_O8  = 7.18623
# H233_S6    = 7.19533
# H288_S13   = 7.21139
# H211_S5    = 7.28006
# H266_S8    = 7.29655
# H21110_Q9  = 7.30380
# H232_O12   = 7.31632
# H288_S12   = 7.32289
# H287_O8    = 7.36855
# H276_O9    = 7.37106
# H255_S7    = 7.37296
# H277_S9    = 7.41846
# H2109_Q13  = 7.45155
# H265_O10   = 7.47591
# H298_O7    = 7.49616
# H2119_O14  = 7.50660
# H288_S11   = 7.51711
# H21412_O4  = 7.58211
# H21110_O4  = 7.59882
# H244_S6    = 7.63987
# H254_O11   = 7.66793
# H221_O13   = 7.67748
# H222_S5    = 7.68371
# H288_S10   = 7.80166
# H2109_O6   = 7.80635
# H21110_Q10 = 7.80672
# H266_S7    = 7.91904
# H277_S8    = 7.92101
# H243_O12   = 7.95264
# H210_O14   = 8.12263
# H233_S5    = 8.12854
# H255_S6    = 8.14723
# H21312_S3  = 8.14802
# H288_S9    = 8.19210
# H2109_Q14  = 8.20242
# H21312_S2  = 8.21533
# H21312_S4  = 8.23995
# H287_O9    = 8.28410
# H276_O10   = 8.31173
# H232_O13   = 8.32145
# H298_O8    = 8.40908
# H21110_O5  = 8.41011
# H21312_S1  = 8.42202
# H21311_O9  = 8.43653
# H211_S4    = 8.45292
# H265_O11   = 8.46116
# H299_S13   = 8.46289
# H299_S12   = 8.47808
# H21110_Q11 = 8.47831
# H21312_S5  = 8.54036
# H21210_O12 = 8.54125
# H277_S7    = 8.57863
# H299_S11   = 8.61118
# H244_S5    = 8.62557
# H288_S8    = 8.71414
# H254_O12   = 8.71423
# H266_S6    = 8.73968
# H2109_O7   = 8.74576
# H221_O14   = 8.78641
# H299_S10   = 8.86191
# H222_S4    = 8.91849
# H243_O13   = 9.09126
# H255_S5    = 9.19116
# H299_S9    = 9.24191
# H210_O15   = 9.36073
# H288_S7    = 9.40813
# H21110_Q12 = 9.41610
# H287_O10   = 9.41643
# H21110_O6  = 9.42199
# H233_S4    = 9.43065
# H277_S6    = 9.45085
# H276_O11   = 9.47594
# H298_O9    = 9.54149
# H232_O14   = 9.56912
# H265_O12   = 9.68355
# H299_S8    = 9.77580
# H266_S5    = 9.84890
# H2109_O8   = 9.92065
# H244_S4    = 10.00254
# H254_O13   = 10.01621
# H221_O15   = 10.17765
# H211_S3    = 10.17771
# H288_S6    = 10.33786
# H21211_Q9  = 10.36689
# H21010_S11 = 10.43191
# H299_S7    = 10.50547
# H243_O14   = 10.52344
# H21010_S10 = 10.53524
# H21010_S12 = 10.53740
# H277_S5    = 10.63459
# H255_S4    = 10.65125
# H222_S3    = 10.73515
# H21010_S9  = 10.83232
# H287_O11   = 10.84535
# H210_O16   = 10.93425
# H276_O12   = 10.94780
# H298_O10   = 10.97393
# H232_O15   = 11.15171
# H265_O13   = 11.23326
# H21010_S8  = 11.33410
# H233_S3    = 11.34751
# H266_S4    = 11.40307
# H2109_O9   = 11.42151
# H299_S6    = 11.49928
# H288_S5    = 11.60781
# H254_O14   = 11.67092
# H21211_Q10 = 11.91844
# H221_O16   = 11.96880
# H244_S3    = 12.03121
# H21010_S7  = 12.07715
# H277_S4    = 12.29775
# H243_O15   = 12.36660
# H287_O12   = 12.69662
# H255_S3    = 12.80432
# H298_O11   = 12.83281
# H276_O13   = 12.86072
# H299_S5    = 12.87086
# H211_S2    = 12.92756
# H210_O17   = 13.00182
# H21010_S6  = 13.13138
# H232_O16   = 13.21774
# H265_O14   = 13.25215
# H288_S4    = 13.39973
# H222_S2    = 13.63240
# H21111_S9  = 13.63339
# H21111_S10 = 13.69379
# H266_S3    = 13.69782
# H254_O15   = 13.82794
# H21111_S8  = 13.94101
# H221_O17   = 14.35944 
# H233_S2    = 14.40590 
# H21111_S7  = 14.60623
# H21010_S5  = 14.61957
# H277_S3    = 14.75801
# H243_O16   = 14.80127
# H299_S4    = 14.81900 
# H287_O13   = 15.17973 
# H244_S2    = 15.26970
# H298_O12   = 15.32788
# H276_O14   = 15.43849
# H265_O15   = 15.97421
# H232_O17   = 16.0282
# H2109_O11  = 16.08950
# H254_O16   = 16.72464
# H211_S1    = 17.93257
# H243_O17   = 18.10926
# H287_O14   = 18.66975
# H298_O13   = 18.83303
# H276O_O15  = 19.08432
# H265_O16   = 19.80825
# H2109_O12  = 19.98130
# H21212_S7  = 20.05775
# H21212_S8  = 20.42270
# H254_O17   = 20.74786
# H21110_O11 = 22.42215
# H287_O15   = 23.90557
# H298_O14   = 24.08191
# H276_O16   = 24.59710
# H265_O17   = 25.52151
# H2109_O13  = 26.08200

# profiles: the type of profile that should be used to fit each line.
# the "default" key sets the default profile, but they can be individually
# overwritten by using the same keys as in the "lines" section
[profiles]
default = "Voigt"

# acomps: specify which, if any, lines to add an additional component, and what type
# of profile it should be. Can add an arbitrary number of additional components.
[acomps]
# NeVI_7652 = ["Voigt"]
# NeII_12813 = ["Voigt"]
# NeIII_15555 = ["Voigt"]
# NeV_14322 = ["Voigt"]
# ArIII_8991 = ["Voigt"]
# SIV_10511 = ["Voigt"]


# optional: add [parameters] key to specify individual line priors that 
# are different from the defaults

# [parameters.NeII_12813]
# acomp_amp_plim = [[0.0, 0.5]]
# acomp_fwhm_plim = [[1.5, 5.0]]

# [parameters.ArIII_8991]
# acomp_amp_plim = [[0.0, 0.5]]
# acomp_fwhm_plim = [[1.5, 5.0]]
# acomp_voff_plim = [[-500.0, -100.0]]
