# lines.toml: This file contains options pertaining to the
# line model of the spectra.

# Tying parameters
tie_voigt_mixing = true     # tie the Voigt mixing ratios of all lines

# Kinematics groups: for each group, every line in the group will have a tied voff and fwhm, just specify which
#                    lines you want in each group

# Tie molecular Hydrogen lines
kinematic_group_H2 = [
    "H200_",
    "H210_"
]

# Atomic hydrogen recombination lines
# kinematic_group_Balmer = [
#     "HI_H_"
# ]
# # Case B recombination amplitude ratios for (Hzeta, Hepsilon, Hdelta, Hgamma, Hbeta, Halpha)
# # You do need to specify individual lines here to make sure the right line gets the right ratio
# [tie_amp_Balmer]
# HI_H_alpha = 2.87
# HI_H_beta = 1.0
# HI_H_gamma = 0.466
# HI_H_delta = 0.256
# HI_H_epsilon = 0.158
# HI_H_zeta = 0.105
# [tie_acomp_1_amp_Balmer]
# HI_H_alpha = 2.87
# HI_H_beta = 1.0
# HI_H_gamma = 0.466
# HI_H_delta = 0.256
# HI_H_epsilon = 0.158
# HI_H_zeta = 0.105


kinematic_group_lo = [
    "HI_",
    "HeI_",
    "ArII_",
    "NeII_",
    "FeII_",
    "OI_",
    "OII_",
    "SII_",
    "SIII_",
    "ClII_",
    "NiII_"
]

kinematic_group_med = [
    "ArIII_",
    "SIV_",
    "MgIV_",
    "ArVI_",
    "OIII_",
    "NeIII_",
    "HeII_",
    "NaIII_"
]

kinematic_group_hi = [
    "NeV_",
    "NeVI_",
    "MgV_",
    "MgVII_",
    "FeVII_",
    "FeVIII_",
    "SiIX_",
    "OVI_"
]

# Lines to make combined flux/eqw maps for
combined_maps = [["OII_3727A", "OII_3729A"]]

# Additional line components
n_acomps = 1
rel_amp = false
rel_voff = false 
rel_fwhm = false

# Default sorting order for lines components: 
# -1 = decreasing (largest first), 1 = increasing (smallest first)
default_sort_order = -1

# Line voff and FWHM limits
[voff]
val = 0.0
plim = [-800.0, 800.0]              # -800 to 800 km/s from the rest wavelength
locked = false

[fwhm]
val = 500.0
plim = [0.0, 2000.0]                # 0 to 1000 km/s FWHM velocity of the line -- this is the *intrinsic* FWHM,
locked = false                      #    i.e. the FWHM after the instrumental FWHM has been subtracted in quadrature
                                   
[h3]
val = 0.0
plim = [-0.5, 0.5]                    # skewness (3rd moment): limits (-0.5, 0.5), to remain mostly gaussian
locked = false

[h4]
val = 0.0
plim = [-0.5, 0.5]                    # kurtosis (4th moment): limits (-0.5, 0.5), to remain mostly gaussian
locked = false

[eta]
val = 1.0                           # start the mixing ratio fully Gaussian
plim = [0.0, 1.0]                    # mixing parameter for Voigt profiles: limits (0.0, 1.0)
locked = true                        # the MIRI/MRS line-spread function should essentially be purely Gaussian

# if rel_amp is set, this is a fraction of the main component amp
# if rel_amp is not set, the acomp_amp values are IGNORED
[[acomp_amp]]
val = 0.1
plim = [0.0, 1.0]
locked = false

# if rel_voff is set, these are velocities relative to the primary component
# if rel_voff is not set, these are velocities relative to the rest wavelength of the line
[[acomp_voff]]
val = 0.0
plim = [-800.0, 800.0]
locked = false

# if rel_fwhm is set, these are multiplicative values on the primary component FWHM
# if rel_fwhm is not set, these are velocities just like the primary FWHM values
[[acomp_fwhm]]
val = 500.0
plim = [0.0, 2000.0]
locked = false

[[acomp_h3]]
val = 0.0
plim = [-0.5, 0.5]
locked = false

[[acomp_h4]]
val = 0.0
plim = [-0.5, 0.5]
locked = false

[[acomp_eta]]
val = 1.0
plim = [0.0, 1.0]
locked = true

# Central wavelengths of each line that should be included in the model, in microns
# Line wavelengths should be *vacuum* wavelengths, not air wavelengths

# Optical Sources:
#   Good general line list for common galaxy emission lines: http://astronomy.nmsu.edu/drewski/tableofemissionlines.html
#    * note: this source has lines in AIR wavelengths for lines above 2000 angstroms, so they must be converted to vacuum wavelengths.

# MIR Sources:
#   Good infrared line lists for HI, H2 and common ions: https://www.mpe.mpg.de/ir/ISO/linelists/
#   Good infrared line lists for HI and H2: https://www.not.iac.es/instruments/notcam/ReferenceInfo/
#   NIST: https://physics.nist.gov/PhysRefData/ASD/lines_form.html 


##################################### UV LINES      ################################################

[lines.HI_Ly_beta]
wave = 1025.722
latex = "Ly$\\beta$"
annotate = true
unit = "angstrom"

[lines.OVI_1032A]
wave = 1031.912
latex = "O $\\textsc{vi}$"
annotate = true
unit = "angstrom"

[lines.OVI_1038A]
wave = 1037.613
latex = "O $\\textsc{vi}$"
annotate = true
unit = "angstrom"

[lines.ArI_1067A]
wave = 1066.660
latex = "[Ar $\\textsc{i}$]"
annotate = true
unit = "angstrom"

[lines.HeII_1085A]
wave = 1084.9
latex = "He $\\textsc{ii}$"
annotate = true
unit = "angstrom"

##################################### OPTICAL LINES ################################################

# Balmer Series (Hydrogen, n -> 2) lines
[lines.HI_H_alpha]
wave = 6564.632
latex = "H$\\alpha$"
annotate = true
unit = "angstrom"

[lines.HI_H_beta]
wave = 4862.691
latex = "H$\\beta$"
annotate = true
unit = "angstrom"

[lines.HI_H_gamma]
wave = 4341.691
latex = "H$\\gamma$"
annotate = true
unit = "angstrom"

[lines.HI_H_delta]
wave = 4102.900
latex = "H$\\delta$"
annotate = true
unit = "angstrom"

[lines.HI_H_epsilon]
wave = 3971.202
latex = "H$\\varepsilon$"
annotate = true
unit = "angstrom"

[lines.HI_H_zeta]
wave = 3890.166
latex = "H$\\zeta$"
annotate = true
unit = "angstrom"

# Helium lines
[lines.HeI_3889A]
wave = 3889.749
latex = "He $\\textsc{i}$"
annotate = true
unit = "angstrom"

[lines.HeII_4687A]
wave = 4687.021
latex = "He $\\textsc{ii}$"
annotate = true
unit = "angstrom"

[lines.HeI_5877A]
wave = 5877.253
latex = "He $\\textsc{i}$"
annotate = true
unit = "angstrom"

[lines.HeI_7067A]
wave = 7067.144
latex = "He $\\textsc{i}$"
annotate = true
unit = "angstrom"

# Neon lines

# [Ne V] doublet
[lines.NeV_3346A]
wave = 3346.783
latex = "[Ne $\\textsc{v}$]"
annotate = true
unit = "angstrom"

[lines.NeV_3426A]
wave = 3426.863
latex = "[Ne $\\textsc{v}$]"
annotate = true
unit = "angstrom"

[lines.NeIII_3869A]
wave = 3869.856
latex = "[Ne $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

[lines.NeIII_3967A]
wave = 3968.593
latex = "[Ne $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

# Oxygen lines

[lines.OIII_3445A]
wave = 3445.039
latex = "O $\\textsc{iii}$"
annotate = true
unit = "angstrom"

# [O II] doublet
[lines.OII_3727A]
wave = 3727.092
latex = "[O $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

[lines.OII_3729A]
wave = 3729.875
latex = "[O $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

[lines.OIII_4364A]
wave = 4364.436
latex = "[O $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

# [O III] doublet
[lines.OIII_4960A]
wave = 4960.295
latex = "[O $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

[lines.OIII_5008A]
wave = 5008.240
latex = "[O $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

[lines.OI_6048A]
wave = 6048.114
latex = "[O $\\textsc{i}$]"
annotate = true
unit = "angstrom"

[lines.OI_06302A]
wave = 6302.046
latex = "[O $\\textsc{i}$]"
annotate = true
unit = "angstrom"

[lines.OI_6366A]
wave = 6365.535
latex = "[O $\\textsc{i}$]"
annotate = true
unit = "angstrom"

[lines.OII_7322A]
wave = 7322.007
latex = "[O $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

[lines.OII_7333A]
wave = 7332.750
latex = "[O $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

# Iron lines
[lines.FeIII_5272A]
wave = 5271.869
latex = "[Fe $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

# [lines.FeXIV_5304A]
# wave = 5304.335
# latex = "[Fe $\\textsc{xiv}$]"
# annotate = true
# unit = "angstrom"

# [lines.FeVI_5639A]
# wave = 5639.165
# latex = "[Fe $\\textsc{vi}$]"
# annotate = true
# unit = "angstrom"

# [lines.FeVI_5679A]
# wave = 5678.575
# latex = "[Fe $\\textsc{vi}$]"
# annotate = true
# unit = "angstrom"

# [lines.FeVII_5722A]
# wave = 5722.287
# latex = "[Fe $\\textsc{vii}$]"
# annotate = true
# unit = "angstrom"

# [lines.FeVII_6088A]
# wave = 6088.685
# latex = "[Fe $\\textsc{vii}$]"
# annotate = true
# unit = "angstrom"

[lines.FeX_6376A]
wave = 6376.272
latex = "[Fe $\\textsc{x}$]"
annotate = true
unit = "angstrom"

[lines.FeXI_7894A]
wave = 7893.971
latex = "[Fe $\\textsc{xi}$]"
annotate = true
unit = "angstrom"

# Sulfur lines
[lines.SII_4069A]
wave = 4069.749
latex = "[S $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

[lines.SII_4077A]
wave = 4077.500
latex = "[S $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

[lines.SIII_6314A]
wave = 6313.806
latex = "[S $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

[lines.SII_6718A]
wave = 6718.294
latex = "[S $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

[lines.SII_6733A]
wave = 6732.668
latex = "[S $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

# Nitrogen lines
[lines.NII_6550A]
wave = 6549.859
latex = "[N $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

[lines.NII_6585A]
wave = 6585.279
latex = "[N $\\textsc{ii}$]"
annotate = true
unit = "angstrom"

# Argon lines
[lines.ArIII_7138A]
wave = 7137.757
latex = "[Ar $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

# Nickel lines
[lines.NiIII_7892A]
wave = 7892.071
latex = "[Ni $\\textsc{iii}$]"
annotate = true
unit = "angstrom"

####################################### IR LINES ##################################################

# Paschen Series (Hydrogen, n -> 3) Lines
[lines.HI_Pa_alpha]
wave = 1.8756133
latex = "Pa$\\alpha$"
annotate = true 
unit = "um"

[lines.HI_Pa_beta]
wave = 1.2821587
latex = "Pa$\\beta$"
annotate = true
unit = "um"

[lines.HI_Pa_gamma]
wave = 1.0941090
latex = "Pa$\\gamma$"
annotate = true 
unit = "um"

[lines.HI_Pa_delta]
wave = 1.0052128
latex = "Pa$\\delta$"
annotate = true 
unit = "um"

# Brackett Series (Hydrogen, n -> 4) Lines
[lines.HI_Br_alpha]
wave = 4.05225
latex = "Br$\\alpha$"
annotate = true
unit = "um"

[lines.HI_Br_beta]
wave = 2.6259
latex = "Br$\\beta$"
annotate = true
unit = "um"

[lines.HI_Br_gamma]
wave = 2.1661
latex = "Br$\\gamma$"
annotate = true
unit = "um"

[lines.HI_Br_delta]
wave = 1.9450871
latex = "Br$\\delta$"
annotate = true 
unit = "um"

# Pfund Series (Hydrogen, n -> 5) Lines
[lines.HI_Pf_alpha]
wave = 7.4599
latex = "Pf$\\alpha$"
annotate = true
unit = "um"

[lines.HI_Pf_beta]
wave = 4.6538
latex = "Pf$\\beta$"
annotate = false
unit = "um"

[lines.HI_Pf_gamma]
wave = 3.7405
latex = "Pf$\\gamma$"
annotate = false
unit = "um"

[lines.HI_Pf_delta]
wave = 3.2970
latex = "Pf$\\delta$"
annotate = false
unit = "um"

[lines.HI_Pf_epsilon]
wave = 3.0392
latex = "Pf$\\varepsilon$"
annotate = false
unit = "um"

# Humphreys Series (Hydrogen, n -> 6) Lines
[lines.HI_Hu_alpha]
wave = 12.372
latex = "Hu$\\alpha$"
annotate = true
unit = "um"

[lines.HI_Hu_beta]
wave = 7.503
latex = "Hu$\\beta$"
annotate = false
unit = "um"

[lines.HI_Hu_gamma]
wave = 5.908
latex = "Hu$\\gamma$"
annotate = false
unit = "um"

[lines.HI_Hu_delta]
wave = 5.129
latex = "Hu$\\delta$"
annotate = false
unit = "um"

[lines.HI_Hu_epsilon]
wave = 4.673
latex = "Hu$\\varepsilon$"
annotate = false
unit = "um"

# Helium Lines
[lines.HeI_1083m]
wave = 1.083331
latex = "He $\\textsc{i}$"
annotate = true
unit = "um"

# Argon Lines
[lines.ArVI_4529m]
wave = 4.529520
latex = "[Ar $\\textsc{vi}$]"
annotate = true
unit = "um"

[lines.ArII_6985m]
wave = 6.985274
latex = "[Ar $\\textsc{ii}$]"
annotate = true
unit = "um"

# [lines.ArV_7901m]
# wave = 7.901600
# latex = "[Ar $\\textsc{v}$]"
# annotate = true
# unit = "um"

[lines.ArIII_8991m]
wave = 8.991380
latex = "[Ar $\\textsc{iii}$]"
annotate = true
unit = "um"

# [lines.ArV_13102m]
# wave = 13.102200
# latex = "[Ar $\\textsc{v}$]"
# annotate = true
# unit = "um"

# Chlorine Lines
[lines.ClII_14368m]
wave = 14.367800
latex = "[Cl $\\textsc{ii}$]"
annotate = true
unit = "um"

# Iron Lines
[lines.FeII_1252m]
wave = 1.257
latex = "[Fe $\\textsc{ii}$]"
annotate = true 
unit = "um"

[lines.FeII_1644m]
wave = 1.644
latex = "[Fe $\\textsc{ii}$]"
annotate = true 
unit = "um"

# [lines.FeII_4889m]
# wave = 4.889137
# latex = "[Fe $\\textsc{ii}$]"
# annotate = true
# unit = "um"

# [lines.FeII_5062m]
# wave = 5.062350
# latex = "[Fe $\\textsc{ii}$]"
# annotate = true
# unit = "um"

[lines.FeII_5340m]
wave = 5.340169
latex = "[Fe $\\textsc{ii}$]"
annotate = true
unit = "um"

[lines.FeVIII_5447m]
wave = 5.4466
latex = "[Fe $\\textsc{viii}$]"
annotate = true
unit = "um"

[lines.FeII_6721m]
wave = 6.721283
latex = "[Fe $\\textsc{ii}$]"
annotate = true
unit = "um"

[lines.FeVII_7814m]
wave = 7.814500
latex = "[Fe $\\textsc{vii}$]"
annotate = true
unit = "um"

[lines.FeVII_9527m]
wave = 9.526700
latex = "[Fe $\\textsc{vii}$]"
annotate = true
unit = "um"

[lines.FeII_17936m]
wave = 17.935950
latex = "[Fe $\\textsc{ii}$]"
annotate = true
unit = "um"

[lines.FeIII_22925m]
wave = 22.925000
latex = "[Fe $\\textsc{iii}$]"
annotate = true
unit = "um"

[lines.FeII_25988m]
wave = 25.988290
latex = "[Fe $\\textsc{ii}$]"
annotate = true
unit = "um"

# Helium Lines
# [lines.HeII_5228m]
# wave = 5.2279972
# latex = "He $\\textsc{ii}$"
# annotate = true
# unit = "um"

# Magnesium Lines
[lines.MgVII_3027m]
wave = 3.027
latex = "[Mg $\\textsc{vii}$]"
annotate = true 
unit = "um"

[lines.MgIV_4867m]
wave = 4.486680
latex = "[Mg $\\textsc{iv}$]"
annotate = true
unit = "um"

[lines.MgVII_5503m]
wave = 5.503200
latex = "[Mg $\\textsc{vii}$]"
annotate = true
unit = "um"

[lines.MgV_5609m]
wave = 5.609850
latex = "[Mg $\\textsc{v}$]"
annotate = true
unit = "um"

[lines.MgVII_9009m]
wave = 9.009000
latex = "[Mg $\\textsc{vii}$]"
annotate = true
unit = "um"

# [lines.MgV_13521m]
# wave = 13.521300
# latex = "[Mg $\\textsc{v}$]"
# annotate = true
# unit = "um"

# Sodium Lines
[lines.NaIII_7318m]
wave = 7.317700
latex = "[Na $\\textsc{iii}$]"
annotate = true
unit = "um"

# Neon Lines
[lines.NeVI_7652m]
wave = 7.652400
latex = "[Ne $\\textsc{vi}$]"
annotate = true
unit = "um"

[lines.NeII_12813m]
wave = 12.813550
latex = "[Ne $\\textsc{ii}$]"
annotate = true
unit = "um"

[lines.NeV_14322m]
wave = 14.321700
latex = "[Ne $\\textsc{v}$]"
annotate = true
unit = "um"

[lines.NeIII_15555m]
wave = 15.555100
latex = "[Ne $\\textsc{iii}$]"
annotate = true
unit = "um"

[lines.NeV_24318m]
wave = 24.317500
latex = "[Ne $\\textsc{v}$]"
annotate = true
unit = "um"

# Nickel Lines
[lines.NiII_6636m]
wave = 6.636000
latex = "[Ni $\\textsc{ii}$]"
annotate = false
unit = "um"

# Oxygen Lines
[lines.OI_1129m]
wave = 1.129
latex = "[O $\\textsc{i}$]"
annotate = true 
unit = "um"

[lines.OIV_25890m]
wave = 25.890300
latex = "[O $\\textsc{iv}$]"
annotate = true
unit = "um"

# Phosphorus Lines
[lines.PIII_17885m]
wave = 17.885000
latex = "[P $\\textsc{iii}$]"
annotate = true
unit = "um"

# Silicon lines
[lines.SiIX_3936m]
wave = 3.935700
latex = "[Si $\\textsc{ix}$]"
annotate = true
unit = "um"

# Sulfur Lines
[lines.SIV_10511m]
wave = 10.510500
latex = "[S $\\textsc{iv}$]"
annotate = true
unit = "um"

[lines.SIII_18713m]
wave = 18.713000
latex = "[S $\\textsc{iii}$]"
annotate = true
unit = "um"

# Molecular Hydrogen Lines
[lines.H210_S5]
wave = 1.8358
latex = "H$_2$ 1-0 $S(5)$"
annotate = false
unit = "um"

[lines.H210_S4]
wave = 1.8920
latex = "H$_2$ 1-0 $S(4)$"
annotate = false 
unit = "um"

[lines.H210_S3]
wave = 1.9576
latex = "H$_2$ 1-0 $S(3)$"
annotate = false 
unit = "um"

[lines.H210_S2]
wave = 2.0338
latex = "H$_2$ 1-0 $S(2)$"
annotate = true
unit = "um"

[lines.H210_S1]
wave = 2.1218
latex = "H$_2$ 1-0 $S(1)$"
annotate = true 
unit = "um"

[lines.H210_S0]
wave = 2.2235
latex = "H$_2$ 1-0 $S(0)$"
annotate = true 
unit = "um"

[lines.H200_S11]
wave = 4.1810
latex = "H$_2$ 0-0 $S(11)$"
annotate = true 
unit = "um"

[lines.H200_S10]
wave = 4.4096
latex = "H$_2$ 0-0 $S(10)$"
annotate = true 
unit = "um"

[lines.H200_S9]
wave = 4.6947
latex = "H$_2$ 0-0 $S(9)$"
annotate = true 
unit = "um"

[lines.H200_S8]
wave = 5.05312
latex = "H$_2$ 0-0 $S(8)$"
annotate = true
unit = "um"

[lines.H200_S7]
wave = 5.51118
latex = "H$_2$ 0-0 $S(7)$"
annotate = true
unit = "um"

[lines.H200_S6]
wave = 6.10857
latex = "H$_2$ 0-0 $S(6)$"
annotate = true
unit = "um"

[lines.H200_S5]
wave = 6.90952
latex = "H$_2$ 0-0 $S(5)$"
annotate = true
unit = "um"

[lines.H200_S4]
wave = 8.02505
latex = "H$_2$ 0-0 $S(4)$"
annotate = true
unit = "um"

[lines.H200_S3]
wave = 9.66492
latex = "H$_2$ 0-0 $S(3)$"
annotate = true
unit = "um"

[lines.H200_S2]
wave = 12.27861
latex = "H$_2$ 0-0 $S(2)$"
annotate = true
unit = "um"

[lines.H200_S1]
wave = 17.03484
latex = "H$_2$ 0-0 $S(1)$"
annotate = true
unit = "um"

[lines.H200_S0]
wave = 28.21883
latex = "H$_2$ 0-0 $S(0)$"
annotate = true
unit = "um"

# profiles: the type of profile that should be used to fit each line.
# the "default" key sets the default profile, but they can be individually
# overwritten by using the same keys as in the "lines" section
[profiles]
default = "Voigt"

# acomps: specify which, if any, lines to add an additional component, and what type
# of profile it should be. Can add an arbitrary number of additional components.
[acomps]

H2 = ["Voigt"]
lo = ["Voigt"]
med = ["Voigt"]
hi = ["Voigt"]

# optional: add [parameters] keywords to specify individual line priors that 
# are different from the defaults

# [parameters]

