# optical.toml: this file contains options pertaining to fitting the
# optical continuum of spectra, including SSPs, extinction, and power laws

################# Stellar Kinematics #################

# Stellar offset velocity (relative to the rest frame given by z)
[stellar_kinematics.vel]
val = 0.0
plim = [-500.0, 500.0]
locked = false

# Stellar velocity dispersion
[stellar_kinematics.vdisp]
val = 100.0
plim = [0.0, 1000.0]
locked = false

################# Fe II Kinematics ###################

[na_feii_kinematics.vel]
val = 0.0
plim = [-500.0, 500.0]
locked = false

[na_feii_kinematics.vdisp]
val = 100.0
plim = [0.0, 500.0]
locked = false

[br_feii_kinematics.vel]
val = 0.0
plim = [-500.0, 500.0]
locked = false

[br_feii_kinematics.vdisp]
val = 1000.0
plim = [500.0, 2000.0]
locked = false


########## Power Law Options ################

# Comment this out to not fit a power law
# [[power_law_indices]]
# val = 0.0
# plim = [-6.0, 6.0]
# locked = false

########## Extinction options ###############

# E(B-V) Reddening factor for the gas
[extinction.E_BV]
val = 0.01
# val = 0.2672455997095422
plim = [0.0, 1.0]
locked = false

# Factor to convert E(B-V) from gas to starlight,
# typically locked to 0.44
# N.b. if you are fitting continuum and lines in separate steps,
# this *must* be locked because it is completely unconstrained
# in the continuum fitting step.
[extinction.E_BV_factor]
val = 0.44
plim = [0.0, 10.0]
locked = true

# Only relevant for Calzetti extinction curves:

# UV bump slope (delta), not fit unless fit_uv_bump is true
[extinction.uv_slope]
val = 0.0
plim = [-0.8, 0.2]
locked = false

# Dust covering fraction, not fit unless fit_covering_frac is true
[extinction.frac]
val = 0.5
plim = [0.0, 1.0]
locked = false
